### ISSUE TITLE
CWEB 4.3 gets out of sync

### ISSUE THREAD

**Issue by ascherer** [ascherer/cweb#26]
The major changes by @texdraft in `CWEB 4.3` (and up) bring `cweave` out of sync with certain constructs like `@=...@>`. See [file var.tar.gz](https://github.com/ascherer/cweb/releases/download/cweb-4.3.1/var.tar.gz) for a small input file and two different output files.

**Comment by texdraft** [comment]
I'm pretty sure that this is the same issue as reported [here](https://github.com/ascherer/cweb/pull/20#issuecomment-809225067).

**Comment by ascherer** [comment]
@texdraft I've amended [the tatball](https://github.com/ascherer/cweb/releases/download/cweb-4.3.1/var.tar.gz) with a short `git` history to easily compare the TeX output of `cweave` **3.64c**, **4.2**, and **4.3**.

I hope to find some time later in the year to dig into `cweave`'s grammar and try to address this – and possibly other – differences.

**Comment by ascherer** [comment]
Looking at the differences in the TeX file created by `cweave` **3.64c**/**4.2** and `cweave` **4.3**, I suspect that even the “old” `cweave` is slightly “off”, although without visual consequences.
```
 \N{1}{1}Test.
 
-\Y\B\8\#\&{include} \.{<stdbool.h>}\6
+\Y\B\1\1\6
+\8\#\&{include} \.{<stdbool.h>}\6
 \vb{\ /*@null@*/\ }\5
-\1\1\&{static} \&{bool} \\{debug}${}\K\\{false};\2\2{}$\6
+\&{static} \&{bool} \\{debug}${}\K\\{false};\2\2{}$\6
 \X2:Structures\X\7
 \X3:Declarations\X\par
 \fi
```
I believe that the `\1\1` group should appear right before the `\vb` macro.

**Comment by texdraft** [comment]
To be fair, that's &ldquo;by design&rdquo;; production 1 puts the indentation after the `exp`. (Usually the `exp` is an identifier when production 1 fires, but here it's the verbatim text.) However, the documentation is incorrect now; the code adds the `dindent` *before* the `exp`.

Preprocessor lines are absorbed into whatever follows them, and this happens before any other production can fire. It is not entirely accurate to say that the `exp` is the verbatim text, since it is really the translation of `#include <stdbool.h>` plus the verbatim text. Therefore the `\1\1` cannot, with the current organization of output, appear immediately adjacent to the `\vb`: If the indentation is placed before the `exp`, then `\1\1` will precede the `#include` line, and if the indentation is placed after the `exp`, then `\1\1` will follow the verbatim text.

----

The following changes appear to fix the problem, although the `\1\1` is still not right before the `\vb`:

```
@x
  make_underlined(pp); big_app(dindent); big_app1(pp);
@y
  make_underlined(pp); big_app1(pp); big_app(dindent);
@z

@x
          if ((a<indent && !(b==big_cancel&&a==' ')) || a>big_force) break;
          if (a==indent) c++;
          else if (a==outdent) c--;
            else if (a==opt) a=get_output();
@y
          if ((a<indent && !(b==big_cancel&&a==' ')) || (a>big_force && a!=dindent)) break;
          if (a==indent) c++;
            else if (a==outdent) c--;
              else if (a==dindent) c+=2;
                else if (a==opt) a=get_output();
@z
```

Note that the documentation is now correct.

**Comment by ascherer** [comment]
@texdraft It works nice, just as `cweave` **3.64c**. Thanks!

**Comment by ascherer** [comment]
@texdraft I've applied [a similar change](https://github.com/ascherer/cweb/commit/d468c47eba15e3e0ffecb86ff6139d1ff72a6ce5) to section 220.

**Comment by ascherer** [comment]
@texdraft I've spotted another bordercase: `make fullmanual` and look at section **25** of `ctangle.dvi` and section **32** of `cweave.dvi`.

**Comment by texdraft** [comment]
Is that not the intended output? There are `@+` commands in the code. But maybe I'm looking for the wrong thing.

**Comment by ascherer** [comment]
No, the second and third function headers are _not_ indented with **CWEB 3.64c** (section **22** in `ctangle.dvi` and section **27** in `cweave.dvi`).
![Screenshot_20210630_162404-ctangle-3 64c](https://user-images.githubusercontent.com/51143/123978248-01147c00-d9c0-11eb-9920-351b4f862cb8.png)
![Screenshot_20210630_162525-cweave-3 64c](https://user-images.githubusercontent.com/51143/123978280-070a5d00-d9c0-11eb-8ca1-beac492e2a1b.png)

**Comment by ascherer** [comment]
@texdraft `git bisect` found the culprit.

**Comment by texdraft** [comment]
OK I see now. The quick diagnosis is that the TeX output has `\1\1\7`, i.e., `dindent big_force`. This should not happen, as specified in section 109 of `CWEAVE`. I'll look into this more in a bit, but I'm guessing that section 220 (and maybe also the `cancel`/`big_cancel` cases in section 217) will have to be changed to look for a `big_force` after a `dindent` and switch them around as necessary.
